apiVersion: v1
kind: Service
metadata:
  name: node-crud-service
  namespace: default
spec:
  selector:
    app: node-crud-service
  type: LoadBalancer
  ports:
  - name: node-crud-service
    protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 3110

